"""
Build the Windows installer for NTE Drive Calc.

Requirements:
    - A PyInstaller app bundle in dist/NTE_Drive_Calc
    - Inno Setup 6 installed, or INNO_SETUP_ISCC pointing to ISCC.exe

Typical usage:
    .\.venv\Scripts\python.exe build_installer.py
    .\.venv\Scripts\python.exe build_installer.py --skip-app-build
    .\.venv\Scripts\python.exe build_installer.py --generate-only
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).parent.resolve()
DIST_APP = ROOT / "dist" / "NTE_Drive_Calc"
APP_EXE = DIST_APP / "NTE_Drive_Calc.exe"
APP_INTERNAL = DIST_APP / "_internal"
INSTALLER_DIR = ROOT / "installer"
OUTPUT_DIR = INSTALLER_DIR / "output"
ISS_PATH = INSTALLER_DIR / "NTE_Drive_Calc.iss"
APP_ICON = ROOT / "assets" / "app_icon.ico"
VIGEM_BUNDLE_EXE = ROOT / "ViGEmBus_1.22.0_x64_x86_arm64.exe"

APP_NAME = "NTE Drive Calc"
APP_EXE_NAME = "NTE_Drive_Calc.exe"
APP_ID = "{{D7DA28BE-8A19-4E05-9216-3F16C4C2C820}"


def _run(cmd: list[str], cwd: Path = ROOT) -> None:
    print("[RUN]", " ".join(cmd))
    subprocess.run(cmd, cwd=str(cwd), check=True)


def _find_iscc() -> Path | None:
    candidates = [
        os.environ.get("INNO_SETUP_ISCC"),
        shutil.which("ISCC.exe"),
        str(Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Inno Setup 6" / "ISCC.exe"),
        r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        r"C:\Program Files\Inno Setup 6\ISCC.exe",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return Path(candidate)
    return None


def _read_app_version() -> str:
    app_path = ROOT / "src" / "ui" / "app.py"
    text = app_path.read_text(encoding="utf-8")
    match = re.search(r'^APP_VERSION\s*=\s*["\']([^"\']+)["\']', text, re.MULTILINE)
    if not match:
        raise RuntimeError(f"APP_VERSION not found in {app_path}")
    return match.group(1)


def _find_vigem_installer() -> tuple[Path, bool]:
    if VIGEM_BUNDLE_EXE.exists():
        return VIGEM_BUNDLE_EXE, True

    try:
        import vgamepad
    except ImportError as exc:
        raise RuntimeError(
            f"ViGEmBus installer not found: {VIGEM_BUNDLE_EXE}. "
            "vgamepad is also not installed, so no fallback MSI is available."
        ) from exc

    pkg_dir = Path(vgamepad.__file__).parent
    msi = pkg_dir / "win" / "vigem" / "install" / "x64" / "ViGEmBusSetup_x64.msi"
    if not msi.exists():
        raise RuntimeError(f"ViGEmBus driver MSI not found: {msi}")
    return msi, False


def _app_process_running() -> bool:
    if os.name != "nt":
        return False
    try:
        result = subprocess.run(
            ["tasklist", "/FI", f"IMAGENAME eq {APP_EXE_NAME}", "/FO", "CSV", "/NH"],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return False
    return APP_EXE_NAME.lower() in result.stdout.lower()


def _ensure_app_bundle(skip_app_build: bool) -> None:
    if skip_app_build:
        if not APP_EXE.exists() or not APP_INTERNAL.exists():
            raise RuntimeError(
                "dist/NTE_Drive_Calc is missing. Run build_exe.py first or omit --skip-app-build."
            )
        return

    if _app_process_running():
        raise RuntimeError(
            f"{APP_EXE_NAME} is currently running. Close it before rebuilding dist/NTE_Drive_Calc, "
            "or use --skip-app-build to package the existing app bundle."
        )

    _run([sys.executable, str(ROOT / "build_exe.py")])
    if not APP_EXE.exists() or not APP_INTERNAL.exists():
        raise RuntimeError("PyInstaller build finished, but dist/NTE_Drive_Calc is incomplete.")


def _inno_path(path: Path) -> str:
    return str(path.resolve())


def _write_iss(version: str, vigem_installer: Path, vigem_is_exe: bool) -> None:
    INSTALLER_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    setup_icon_line = f"SetupIconFile={_inno_path(APP_ICON)}\n" if APP_ICON.exists() else ""
    vigem_dest_name = "ViGEmBus_Setup.exe" if vigem_is_exe else "ViGEmBusSetup_x64.msi"
    vigem_file_line = (
        f'Source: "{_inno_path(vigem_installer)}"; DestDir: "{{app}}\\drivers"; '
        f'DestName: "{vigem_dest_name}"; Flags: ignoreversion'
    )
    if vigem_is_exe:
        vigem_install_filename = "{app}\\drivers\\ViGEmBus_Setup.exe"
        vigem_install_params = "/qn /norestart"
    else:
        vigem_install_filename = "{sys}\\msiexec.exe"
        vigem_install_params = (
            '/i "{app}\\drivers\\ViGEmBusSetup_x64.msi" '
            "/qn /norestart REINSTALL=ALL REINSTALLMODE=amus"
        )
    vigem_install_params = vigem_install_params.replace('"', '""')

    content = f"""; Generated by build_installer.py. Do not edit by hand.
#define MyAppName "{APP_NAME}"
#define MyAppVersion "{version}"
#define MyAppPublisher "NTE"
#define MyAppExeName "{APP_EXE_NAME}"

[Setup]
AppId={APP_ID}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
DefaultDirName={{autopf}}\\NTE Drive Calc
DefaultGroupName={{#MyAppName}}
DisableProgramGroupPage=yes
OutputDir={_inno_path(OUTPUT_DIR)}
OutputBaseFilename=NTE_Drive_Calc_Setup_{{#MyAppVersion}}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
{setup_icon_line}PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={{app}}\\{{#MyAppExeName}}
CloseApplications=yes
CloseApplicationsFilter=NTE_Drive_Calc.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"
Name: "installvigem"; Description: "Install ViGEmBus virtual gamepad driver"; GroupDescription: "Runtime dependencies:"; Flags: checkedonce

[Files]
Source: "{_inno_path(APP_EXE)}"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "{_inno_path(APP_INTERNAL)}\\*"; DestDir: "{{app}}\\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
{vigem_file_line}

[Dirs]
Name: "{{app}}\\config"; Permissions: users-modify
Name: "{{app}}\\logs"; Permissions: users-modify
Name: "{{app}}\\scanned_images"; Permissions: users-modify

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; WorkingDir: "{{app}}"
Name: "{{group}}\\Install ViGEmBus Driver"; Filename: "{vigem_install_filename}"; Parameters: "{vigem_install_params}"; WorkingDir: "{{app}}"; Check: IsWin64
Name: "{{group}}\\Uninstall {{#MyAppName}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; WorkingDir: "{{app}}"; Tasks: desktopicon

[Run]
Filename: "{vigem_install_filename}"; Parameters: "{vigem_install_params}"; StatusMsg: "Installing or repairing ViGEmBus virtual gamepad driver..."; Flags: waituntilterminated; Tasks: installvigem; Check: ShouldInstallViGEmBus
Filename: "{{cmd}}"; Parameters: "/C sc start ViGEmBus >NUL 2>NUL & exit /B 0"; StatusMsg: "Starting ViGEmBus driver service..."; Flags: runhidden waituntilterminated; Tasks: installvigem; Check: IsWin64
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent runascurrentuser

[Code]
function ShouldInstallViGEmBus: Boolean;
begin
  Result := IsWin64 and WizardIsTaskSelected('installvigem');
end;
"""
    ISS_PATH.write_text(content, encoding="utf-8")
    print(f"[OK] Wrote installer script: {ISS_PATH}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build NTE Drive Calc installer.")
    parser.add_argument("--version", default=os.environ.get("APP_VERSION") or _read_app_version())
    parser.add_argument("--skip-app-build", action="store_true", help="Use existing dist/NTE_Drive_Calc.")
    parser.add_argument("--generate-only", action="store_true", help="Generate .iss but do not run Inno Setup.")
    args = parser.parse_args()

    try:
        _ensure_app_bundle(skip_app_build=args.skip_app_build)
        vigem_installer, vigem_is_exe = _find_vigem_installer()
        _write_iss(version=args.version, vigem_installer=vigem_installer, vigem_is_exe=vigem_is_exe)

        if args.generate_only:
            print("[OK] Generate-only mode complete.")
            return 0

        iscc = _find_iscc()
        if not iscc:
            print("[WARN] Inno Setup compiler was not found.")
            print("[WARN] Install Inno Setup 6, or set INNO_SETUP_ISCC to ISCC.exe.")
            print("[WARN] Then run: .\\.venv\\Scripts\\python.exe build_installer.py --skip-app-build")
            return 2

        _run([str(iscc), str(ISS_PATH)])
        setup = OUTPUT_DIR / f"NTE_Drive_Calc_Setup_{args.version}.exe"
        if not setup.exists():
            raise RuntimeError(f"Installer build finished, but output was not found: {setup}")
        print(f"[OK] Installer complete: {setup}")
        return 0
    except subprocess.CalledProcessError as exc:
        print(f"[FAIL] Command failed with exit code {exc.returncode}")
        return exc.returncode
    except Exception as exc:
        print(f"[FAIL] {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
